version: '3.8'

services:
  app:
    build: ./docker
    restart: always
    tty: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8000:80"
    volumes:
      - ./app:/code/app